Cinch\CoreBundle\Entity\Region:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        alias:
            type: string
            length: 255
        template:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    oneToMany:
        blocks:
            targetEntity: Block
            mappedBy: region
    manyToOne:
        page:
            targetEntity: Page
            inversedBy: regions