parameters:
#    cinch_installer.example.class: Cinch\InstallerBundle\Example

services:
#    cinch_installer.example:
#        class: %cinch_installer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
